victoricoma/helprback

- helprback/mysql/empregados/Script de Procedires e Tabelas Temporarias.sql
- helprback/pom.xml
- helprback/src/main/java/com/api/helprback/HelprbackApplication.java
> Montagem do projeto inicial do back

- helprback/src/main/java/com/api/helprback/domain/Pessoa.java
- helprback/src/main/java/com/api/helprback/domain/enums/Perfil.java
- helprback/src/main/java/com/api/helprback/domain/enums/Prioridade.java
- helprback/src/main/java/com/api/helprback/domain/enums/Status.java
> Adição das classes enumeradoras do sistema.

- helprback/src/main/java/com/api/helprback/domain/Chamado.java
- helprback/src/main/java/com/api/helprback/domain/Cliente.java
- helprback/src/main/java/com/api/helprback/domain/Tecnico.java
> Nova estrutura de classes base MySQL

- helprback/src/main/java/com/api/helprback/domain/Chamado.java
- helprback/src/main/java/com/api/helprback/domain/Cliente.java
- helprback/src/main/java/com/api/helprback/domain/Pessoa.java
- helprback/src/main/java/com/api/helprback/domain/Tecnico.java
- helprback/src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Estruturação das classes para persistência de Entidades.

- helprback/src/main/resources/application.properties
> Conexão das classes com os dados no H2 console.

- helprback/src/main/java/com/api/helprback/HelprbackApplication.java
- helprback/src/main/java/com/api/helprback/repositories/ChamadoRepository.java
- helprback/src/main/java/com/api/helprback/repositories/ClienteRepository.java
- helprback/src/main/java/com/api/helprback/repositories/PessoaRepository.java
- helprback/src/main/java/com/api/helprback/repositories/TecnicoRepository.java
> Injeção de dados no banco de h2 testes.

- helprback/src/main/java/com/api/helprback/HelprbackApplication.java
- helprback/src/main/java/com/api/helprback/config/TestConfig.java
- helprback/src/main/java/com/api/helprback/services/DBService.java
- helprback/src/main/resources/application-test.properties
- helprback/src/main/resources/application.properties
> Modulação de dados para serviços e configuradores.

- helprback/src/main/java/com/api/helprback/domain/Pessoa.java
- helprback/src/main/java/com/api/helprback/domain/Tecnico.java
- helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
- helprback/src/main/java/com/api/helprback/services/TecnicoService.java
- helprback/src/main/resources/application-dev.properties
> Adição dos serviço e recurso de listagem por id em tecnico.

- helprback/src/main/java/com/api/helprback/domain/dtos/TecnicoDTO.java
- helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
> Montagem e configuração dos dados da classe DTO.

- helprback/src/main/java/com/api/helprback/resources/exceptions/ResourceExceptionHandler.java
- helprback/src/main/java/com/api/helprback/resources/exceptions/StandardError.java
- helprback/src/main/java/com/api/helprback/services/TecnicoService.java
- helprback/src/main/java/com/api/helprback/services/exceptions/ObjectNotFoundException.java
> Tratamento de bug de erro para entrega ao front.

- helprback/src/main/java/com/api/helprback/domain/Tecnico.java
- helprback/src/main/java/com/api/helprback/domain/dtos/TecnicoDTO.java
- helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
- helprback/src/main/java/com/api/helprback/services/TecnicoService.java
- helprback/src/main/resources/application.properties
> Listagem geral e criação de Tecnicos.

- helprback/src/main/java/com/api/helprback/repositories/PessoaRepository.java
- helprback/src/main/java/com/api/helprback/resources/exceptions/ResourceExceptionHandler.java
- helprback/src/main/java/com/api/helprback/services/TecnicoService.java
- helprback/src/main/java/com/api/helprback/services/exceptions/DataIntegrityViolationException.java
> Validação no insert de CPF e E-mail

- helprback/src/main/java/com/api/helprback/domain/Pessoa.java
- helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
- helprback/src/main/java/com/api/helprback/services/TecnicoService.java
> Adição do update de Tecnico ao serviço e recurso na API

- helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
- helprback/src/main/java/com/api/helprback/services/TecnicoService.java
> Adição do recurso e serviço de delete do técnico.

- helprback/src/main/java/com/api/helprback/domain/Cliente.java
- helprback/src/main/java/com/api/helprback/domain/dtos/ClienteDTO.java
- helprback/src/main/java/com/api/helprback/resources/ClienteResource.java
- helprback/src/main/java/com/api/helprback/services/ClienteService.java
> CRUD de cliente exercício prático.

- helprback/src/main/java/com/api/helprback/domain/dtos/ChamadoDTO.java
- helprback/src/main/java/com/api/helprback/resources/ChamadoResource.java
- helprback/src/main/java/com/api/helprback/services/ChamadoService.java
> Serviço de relatório do Chamado por Id com relacionamento.

- helprback/src/main/java/com/api/helprback/domain/dtos/TecnicoDTO.java
- helprback/src/main/java/com/api/helprback/resources/ChamadoResource.java
- helprback/src/main/java/com/api/helprback/services/ChamadoService.java
> Listagem geral de Chamados para tabela.

- helprback/src/main/java/com/api/helprback/domain/dtos/ChamadoDTO.java
- helprback/src/main/java/com/api/helprback/resources/ChamadoResource.java
- helprback/src/main/java/com/api/helprback/services/ChamadoService.java
> Adição de novos chamados com relacionamento conferido.

- helprback/src/main/java/com/api/helprback/domain/Chamado.java
- helprback/src/main/java/com/api/helprback/resources/ChamadoResource.java
- helprback/src/main/java/com/api/helprback/services/ChamadoService.java
> Adição da manipulação de dados.

- helprback/pom.xml
- helprback/src/main/java/com/api/helprback/config/SecurityConfig.java
- helprback/src/main/resources/application-dev.properties
> Deeploy do banco e segurança de endpoint.

- helprback/src/main/java/com/api/helprback/config/SecurityConfig.java
- helprback/src/main/java/com/api/helprback/security/UserSS.java
- helprback/src/main/java/com/api/helprback/services/ClienteService.java
- helprback/src/main/java/com/api/helprback/services/DBService.java
- helprback/src/main/java/com/api/helprback/services/TecnicoService.java
> Adição dos serviços de identificação de usuário.

- helprback/src/main/java/com/api/helprback/domain/dtos/CredenciaisDTO.java
- helprback/src/main/java/com/api/helprback/security/JWTUtil.java
- helprback/src/main/java/com/api/helprback/services/UserDetailsServiceImpl.java
- helprback/src/main/resources/application.properties
> Chaves de credenciais e token construtor.

- helprback/src/main/java/com/api/helprback/config/SecurityConfig.java
- helprback/src/main/java/com/api/helprback/security/JWTAuthenticationFilter.java
> JWT token de autenticação e métodos de acesso http.

- helprback/src/main/java/com/api/helprback/config/SecurityConfig.java
- helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
- helprback/src/main/java/com/api/helprback/security/JWTAuthenticationFilter.java
- helprback/src/main/java/com/api/helprback/security/JWTAuthorizationFilter.java
- helprback/src/main/java/com/api/helprback/security/JWTUtil.java
- helprback/src/main/java/com/api/helprback/security/UserSS.java
- helprback/src/main/resources/application.properties
> Aplicação interna de regras de transito na aplicação.

- helprback/system.properties
> Configuração de deploy para o Heroku.

- src/main/resources/application.properties
> Construção do banco no Azure MySQL

- src/main/resources/application-dev.properties
> Inicialização do banco.

- mysql/script_helpr/sps_relatorio_andamento_tecnico_semanal.sql
- src/main/java/com/api/helprback/repositories/ChamadoRepository.java
> Interligação de relatórios de procedures.

- src/main/java/com/api/helprback/resources/ChamadoResource.java
- src/main/java/com/api/helprback/services/ChamadoService.java
- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Relatório de chamados por técnico na semana.

- src/main/java/com/api/helprback/repositories/TecnicoRepository.java
- src/main/java/com/api/helprback/resources/TecnicoResource.java
- src/main/java/com/api/helprback/services/TecnicoService.java
- src/test/java/com/api/helprback/HelprbackApplicationTests.java
Adição de métodos em Técnico: 
Adição de testes:
> Adição do Relatório de Técnicos com chmados urgentes.

- mysql/script_helpr/sps_relatorio_status_chamados_tecnicos.sql
> Script de procedure de contagem de chamados por status.

- mysql/script_helpr/trigger_update_status_chamado.sql
> Tabela de log do status do chamado e criação do trigger de alteração status

- mysql/script_helpr/sps_chamados_andamento_semanal.sql
> Criacao Procedure para chamar com chamados em andamento semana

- mysql/script_helpr/tg_log_chamado_alteracao_prioridade.sql
> Gatilho e tabela de LOG

- mysql/script_helpr/trg_relatorio_pessoa_perfil.sql
Arquivos novos:
trg_relatorio_pessoa_perfil.mysql
> Criação de tabela de log e triggers para perfis em pessoas.

- src/main/java/com/api/helprback/repositories/ChamadoRepository.java
- src/main/java/com/api/helprback/resources/ChamadoResource.java
- src/main/java/com/api/helprback/services/ChamadoService.java
> Chamado Tecnico ultimos três dias.

- mysql/script_helpr/sps_chamado_aberto_cliente.sql
> Procedure chamados abertos

- mysql/script_helpr/sps_relatorio_chamados_prioridade_tecnico.sql
> Criação de procedure para relatório de chamado de técnicos agrupados por prioridade.

- src/main/java/com/api/helprback/domain/LogUpdateStatus.java
- src/main/java/com/api/helprback/repositories/LogUpdateStatusRepository.java
- src/main/java/com/api/helprback/resources/ChamadoResource.java
- src/main/java/com/api/helprback/services/ChamadoService.java
> Endpoints para a entrega da listagem de logs

- mysql/script_helpr/sps_chamados_ultimos_tres_dias.sql
> Procedure Chamados Ultimos Tres Dias de cada Tecnico.

- src/main/java/com/api/helprback/repositories/ChamadoRepository.java
> Correção do direcionamento da Query.

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Implementação de teste para testar o retorno de findByEmail em pessoas.

- mysql/script_helpr/trigger_update_status_chamado.sql
> Correção do Trigger de alteração de status de chamados

- mysql/script_helpr/sps_chamados_urgentes_prioridade_alta_tres_dias.sql
> banco de dados- chamados urgentes

- src/main/java/com/api/helprback/config/SecurityConfig.java
- src/main/java/com/api/helprback/domain/NovosClientes.java
- src/main/java/com/api/helprback/domain/dtos/NovosClientesDTO.java
- src/main/java/com/api/helprback/repositories/NovosClientesRopository.java
- src/main/java/com/api/helprback/resources/NovosClientesResource.java
- src/main/java/com/api/helprback/services/NovosClientesService.java
> Adição de crud para novos clientes.

- mysql/script_helpr/sps_relatorio_pessoa_perfil.sql
> Adição de uma procedure que traga alteração de perfil de pessoa em intervalo de datas.

- mysql/script_helpr/sps_relatorio_chamados_prioridade_tecnico.sql
- src/main/java/com/api/helprback/domain/RelatorioBaseTecnicoChamado.java
- src/main/java/com/api/helprback/repositories/RelatorioBaseTecnicoChamadoRepository.java
- src/main/java/com/api/helprback/resources/RelatorioBaseTecnicoChamadoResource.java
- src/main/java/com/api/helprback/services/RelatorioBaseTecnicoChamadoService.java
> Adição do Endpoint do relatório agrupado por prioridade e atualização da procedure. 

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> "Teste de endpoint para o relatorio de chamados por Tecnico"

- src/main/java/com/api/helprback/resources/ChamadoResource.java
- src/main/java/com/api/helprback/resources/ClienteResource.java
- [] Ajuste de acesso de acordo com as ROLE_ADMIN, ROLE_CLIENTE, ROLE_TECNICO nas pré-autorizações.
> Pre Autorizacoes back

- mysql/script_helpr/sps_chamados_urgentes_prioridade_alta_tres_dias.sql
> Correção da procedure de chamados de prioridade alta dos últimos três dias

- mysql/script_helpr/sps_relatorio_aberto_tecnico_tres_dias.sql
- src/main/java/com/api/helprback/repositories/ChamadoRepository.java
- src/main/java/com/api/helprback/resources/ChamadoResource.java
- src/main/java/com/api/helprback/services/ChamadoService.java
> Endpoint para proc de Chamados status aberto

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Teste entrega de serviço chamado aberto e prioridade alta

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> criacao de teste relatorio montagem chamados

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Foi criado um endpoint para o teste de futuros candidatos.

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Criação de teste listagem com e sem ID.

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Teste Chamados Ultimos Tres Dias.

- mysql/script_helpr/sps_chamado_prioridade.sql
> Adição de uma procedure que traga alteração de prioridade de chamado em um intervalo de datas.

- mysql/script_helpr/sps_alteracao_cliente_tecnico.sql
> Adição de uma procedure que traga alteração de cliente e técnicos nos chamado, em intervalo de datas.

- src/main/java/com/api/helprback/repositories/ChamadoRepository.java
- src/main/java/com/api/helprback/resources/ChamadoResource.java
- src/main/java/com/api/helprback/services/ChamadoService.java
> Criação do endpoint para chamados urgentes dos últimos 3 dias por id do técnico

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Adição do teste de ChamadoByCLienteId

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Testagem concluída do relatório dos 3 dias para um técnico.

- src/main/java/com/api/helprback/domain/Mensagem.java
- src/main/java/com/api/helprback/domain/Tecnico.java
- src/main/java/com/api/helprback/domain/dtos/MensagemDTO.java
> Dominio Mnesagem.

- src/main/java/com/api/helprback/repositories/ChamadoRepository.java
- src/main/java/com/api/helprback/resources/ChamadoResource.java
- src/main/java/com/api/helprback/services/ChamadoService.java
> Endpoint de cliente logado/token.

- src/main/java/com/api/helprback/domain/LogPessoa.java
- src/main/java/com/api/helprback/domain/dtos/LogPessoaDTO.java
- src/main/java/com/api/helprback/repositories/LogPessoaRepository.java
- src/main/java/com/api/helprback/resources/LogPessoaResource.java
- src/main/java/com/api/helprback/services/LogPessoaService.java
> adicao de endpoint troca de perfil

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Adição do testNovosClientesFindAll

- src/test/java/com/api/helprback/HelprbackApplicationTests.java
> Criação de teste para futuros clientes.
